### ISSUE TITLE
Bad contact number in WA (Argentina loqui v 0.2.3)

### ISSUE THREAD

**Issue by deimidis** [loqui/im#159]
I installed the new version, and works perfect for authentication and send messages, but still have problems with phone numbers and contacts.

I have another SIM to test loqui in keon, so I have my own contact in this phone with int.code. When I selected that contact and see the info loqui shows (from whatsapp) says my number in this way: 54911xxxx-xxxx@s.whatsapp.net and shows like unavailable.

But when I send a message from that phone to the keon, the number appear like 54911xxxxxxxx@s.whatsapp.net (without the dash)

**Comment by Gioyik** [comment]
Seems that is the same that someone mentioned in #154. The third point.

**Comment by deimidis** [comment]
No, it's not the same. This is not the validation code from WA, is the number that appear in the contact list vs the number that came from WA message. To add, in the contact app appear without the dash, I don't know when the dash is add, if it's in the contact app or in loqui

**Comment by Gioyik** [comment]
Sorry I was confused with that. Thanks for the explanation. Another question, only that number has the dash there? or all your contacts are with the dash?

**Comment by deimidis** [comment]
All the Argentina's contact has the dash there. But a contact from Venezuela has 58xxx-xxxxxxx From Colombia seems ok, without dash

**Comment by Gioyik** [comment]
Yes, i was seeing that my contacts (in Colombia) are correct, without the dash.

**Comment by deimidis** [comment]
We tested with @Gioyik and with Colombia numbers works

**Comment by aesedepece** [comment]
I think this is already fixed in 0.2.4 by commit 2609ea320bfaba43c1f31254a5bb3d2e562c5250.

**Comment by deimidis** [comment]
Yes, this problem is fixed, but I found another problem (that could be mine :)) Phones that don't wasn't wrote with International codes doesn't were recognized.

Example:
International number for Argentina is +54 but for mbile, you have to add a 9 before the area code. So the final number is something like +54911xxxxxxxx and whatsapp use that rule to create the user. 

But if you have your contact added like +5411xxxxxxxx phone calls works, but Loqui try to find this user, not adding the 9, so it couldn't find the user on whatsapp. Maybe at the same time we check for dashes, we could check for the correct way to write numbers (i think you use another library to make this, right?)

**Comment by aesedepece** [comment]
@deimidis Yes, we are using a library for handling international number format and validation, and I can't understand why in the hell it doesn't fix all the cases.

Adding special rules for certain locales sounds to me more like a cheat than an actual fix.

Sorry for the rant, I say this without any intention of offending anyone; but I'm getting tired of those "magical prefixes" you use in South America. What were govs and carriers thinking of when they designed each national dial plan?

**Comment by Gioyik** [comment]
@aesedepece they thought in fuck us :)

**Comment by deimidis** [comment]
@aesedepece don't worry, I don't feel offended. I rant the same way the first I had to call someone from outside Argentina and had to learn this stupid thing

**Comment by deimidis** [comment]
I could confirm that adding the 9 to contact app, Loqui import correctly the users and works

**Comment by bdcomp** [comment]
@aesedepece It looks like this issue been fixed months ago...
