### ISSUE TITLE
AGPL license text (Settings Info) not visible/access able

### ISSUE THREAD

**Issue by ghost** [loqui/im#458]
I noticed after the additional changelog link #455 is the text of the AGPL not access able at all. It is not possible to scroll down to the license text.

![info](https://cloud.githubusercontent.com/assets/4523264/3561226/b6b68e32-09b0-11e4-9a8a-9998b2f8b419.png)

No AGPL license text visible
![info_no_agpl_text](https://cloud.githubusercontent.com/assets/4523264/3561227/b6bf574c-09b0-11e4-8ef5-2d439fa09769.png)

before #455 
![info_old](https://cloud.githubusercontent.com/assets/4523264/3561228/b6c7a42e-09b0-11e4-89e6-89596811f5e6.png)

**Comment by Gioyik** [comment]
@bdcomp Do you know what could happen?

**Comment by bdcomp** [comment]
No, and in fact, I am curious how a simple html line of code could do this.

Although, while the Info screen is of "scroll" css class, there is no such class in the index.css

**Comment by ghost** [comment]
i am not sure why but adding a `<p>`-tag fix this problem

```
<p><small data-l10n-id='FreeSoftware'>This program is free software; you may redistribute and/or modify it under the terms of the GNU Affero General Public License (AGPL 3) as published by the Free Software Foundation.</small></p>
```

And this problem is not caused by adding a html line, it only gets visible through it, as i couldn't reach the text before if the screen is toppled

**Comment by bdcomp** [comment]
Done!

@aesedepece I am still wondering about the "scroll" css class.
Shouldn't this be exist?

**Comment by ghost** [comment]
@bdcomp 

The fix #460 does not fix the problem with a toppled screen. I can't access the text at all. 

The scroll-class is already added but something within the simple-class might be the problem

```
<article id='info' class='simple scroll'>
```

**Comment by bdcomp** [comment]
@bobcanthelpyou What do you mean by "toppled screen"?

**Comment by ghost** [comment]
that screen:
![info_no_agpl_text](https://cloud.githubusercontent.com/assets/4523264/3561227/b6bf574c-09b0-11e4-8ef5-2d439fa09769.png)

**Comment by aesedepece** [comment]
The `scroll` class is defined in `/style/loqui/chungo.css` as follows:

``` CSS
.scroll {
    overflow: auto;
    will-animate: scroll;
}
```

**Comment by ghost** [comment]
This problem appears again and is caused by **height: calc(100% - 6rem)!important;** within index.css. If i disable the height, everything is fine on the Info page

Why is the height calculated in that way?

```
section.extended article {
  top: 6rem;
  height: calc(100% - 6rem)!important;
}
```
