### ISSUE TITLE
App.exportData() doesn't work any more

### ISSUE THREAD

**Issue by tibtab** [loqui/im#914]
Cloned and builded v0.4.12a and tried to import my data, first my phone asked me to allow loqui the access to the sdcard but loqui doesn't open the folder to choose the backup.

**Comment by TitanNano** [comment]
are you talking about import or export? your title says export, but your description sounds like importing data....

**Comment by tibtab** [comment]
Oh, yeah sorry, I ment import Data.

**Comment by TitanNano** [comment]
I just exported and tried to import again. no problem here. The list with the backups shows up. Did you do an export before? 
I just had to notice that some how the path for the backups changed. I'll fix that but at the moment backups are stored under 'loqui/backup' instead of 'loqui/backups' so maybe your existing backups from previous version can't be found.

**Comment by tibtab** [comment]
ah ok, that will be the problem, with the wrong path. Thanks

**Comment by TitanNano** [comment]
I just fixed the path, so if you rebuild it should work.

**Comment by tibtab** [comment]
still not working :/ maybe the backup-file is with 6.57 MB to big?

**Comment by TitanNano** [comment]
I'm not sure. did you do a pull before you rebuild?

**Comment by tibtab** [comment]
I deleted the build I downloaded this afternoon and cloned it with your changes. Do you ment this with "pull"? But I also tried to rename the folder in which the file is stored. It doesn't worke either.

**Comment by TitanNano** [comment]
yes there was a slash too much in the path for the backup directory. I tested it and it works for me now. 
if you cloned the repository you can simply go into your local repository folder and do a `git pull` in your comand line. This will download all new changes.

**Comment by tibtab** [comment]
ok, to late to try this, I already deleted the prvious one.
But now the importing works again :)
thank you
