### ISSUE TITLE
cant recieve texts from contacts

### ISSUE THREAD

**Issue by botswan** [loqui/im#988]
Um only able to send texts and when people reply the texts dont reach me only group texts come and after long time and they keep repeating soo many times. Can i get help

**Comment by maatla** [comment]
I cant receive texts from my contacts

**Comment by cmeerw** [comment]
Does anyone have any log files?

**Comment by YunitoMH** [comment]
Not yet, but today I noticed this issue, its annoying 

Edit: It is solved with the new update 0.5.2

**Comment by petzichen** [comment]
I think the bug is back there since yesterday. Could it be that the end-to-end encryption is the cause now!? I can only recieve images (I think other media, too).

**Comment by cmeerw** [comment]
Could be, but how to tell without debug logs?

**Comment by petzichen** [comment]
I will see what I can do today (in the afternoon)...
[Marketplace-Version]

**Comment by petzichen** [comment]
Here an image...
[http://new.loox.tools/fxos/b1.png](http://new.loox.tools/fxos/b1.png)
A bigger log in detail: 
[http://new.loox.tools/fxos/b2.log](http://new.loox.tools/fxos/b2.log)
- xx05 = my Number in Loqui!

**Comment by cmeerw** [comment]
@petzichen Unfortunately, that doesn't show the root cause (which happened sometime before and cause the decryption queue to stop...)

BTW, do you happen to have an official WhatsApp client? If so, could you send an image to +447494848265 please?

**Comment by petzichen** [comment]
@cmeerw I'm only using "Andy" on my windows-notebook... Simple and easy... Just fine. Why do you need an image? It's a virtual machine of android with the offical app from Play-Store 😕
I don't have anything else for logs :-/

**Comment by cmeerw** [comment]
Well, I don't have Windows here... Image would be nice to debug image reception - you can also send me a text message, but I believe text message work fine in the current version.

**Comment by petzichen** [comment]
Hm... Yes, okay. I can look tomorrow for that; I'm not at home at the moment.

Note: It could be that I got only two images by my contacts. Now I receive nothing more... 😲

// I sent an image and a text message to you, @cmeerw.

**Comment by Bapalele** [comment]
I can send massage but can't receive from other contacts i really need help pliz

**Comment by cmeerw** [comment]
What phone do you have?

Also please see https://github.com/loqui/im/wiki/Reporting-Bugs

**Comment by yassminamohamed** [comment]
I stell can't recieve any messages in v5.5.0

**Comment by MomenAtta** [comment]
I also I can not receive any text messages Does anyone arrived to a solution ?

**Comment by cmeerw** [comment]
@MomenAtta you might have to update to 0.5.6...
